### ISSUE TITLE
Preroll Media path issues

### ISSUE THREAD

**Issue by saskskrat** [chadwpalm/PrerollPlus#3]
I have a windows machine running all of my Arrs and Preroll Plus.

the Prerolls and PLEX are stored/running on a Synology NAS,
I installed Preroll Plus natively on the Windows machine, and have set the location of preroll media using the ip of the nas in the path, "\\192.168.128.62\Data\PLEXTRAS\Prerolls"

the Plex location of preroll media is greyed out and cannot be edited - as I had installed natively.

When it is triggered the path of the files are saved in plex with the full path of each file, whereas it works properly when the path is saved as \volume1\DATA\PLEXTRAS\Prerolls\filename.mp4

**Comment by chadwpalm** [comment]
I just pushed an update v0.1.3 into the develop branch. This update should give you what you need for it to work properly in Native install. The "Plex location of preroll media" shouldn't be grayed out anymore and that will be the root location of your preroll files as Plex sees them and what gets propagated into the Preroll path in the Plex settings.

Go ahead and try it out and let me know if this is the solution you were looking for.

Chad

**Comment by saskskrat** [comment]
That allowed me to get it working. Thanks!
