### ISSUE TITLE
Missing 'latest' tag in Docker Registry

### ISSUE THREAD

**Issue by drewstopherlee** [chadwpalm/PrerollPlus#9]
There is no latest tag available in the Docker registry. When I try to `docker pull chadwpalm/prerollplus` or `docker pull chadwpalm/prerollplus:latest`, I get the following error:
```
Error response from daemon: manifest for chadwpalm/prerollplus:latest not found: manifest unknown: manifest unknown
```

When checking the Docker Hub tags, there is no 'latest' tag.

I fixed the issue by pulling the 'develop' tag.

**Comment by chadwpalm** [comment]
The app is still in the development and beta stage. Until it is fully released it will remain in the develop branch/tag. Once released it will then have a latest tag.

I'm working on the last of the initial features I want to add in before release. Hopefully in the next couple of weeks.

**Comment by drewstopherlee** [comment]
Maybe consider adding a temporary notice to the documentation with that info?

**Comment by chadwpalm** [comment]
Yeah, I can temporarily place it in the readme file until I release. I had mentioned it in my Reddit post, but I don't think very many people read the whole thing lol.

**Comment by drewstopherlee** [comment]
> I don't think very many people read the whole thing lol.

Guilty lol. I read some of it, was interested, and starred the repo for later. Thanks for being so responsive!

**Comment by chadwpalm** [comment]
No problem. I'm going to roll out another update tomorrow which will probably be the last one for beta, then if there aren't any issues I'll roll that into the first release probably sometime next week.

**Comment by drewstopherlee** [comment]
Excellent! I'll go ahead and close this then. Btw, do you have a preferred channel for feature requests?
